export const PUBLICATION_MARKDOWN_PATH = "docs/dou/UKRAINIAN_PUBLICATION_DRAFT.md";
export const PUBLICATION_STUB_PATH = "UKRAINIAN_PUBLICATION.md";
export const PUBLICATION_GOOGLEDOCS_PATH = "UKRAINIAN_PUBLICATION_GOOGLEDOCS.txt";
export const EXAMPLES_OUTPUT_PATH = "EXAMPLES_OUTPUT.txt";
